### ISSUE TITLE
系统变量问题请教

### ISSUE THREAD

**Issue by Guochengjie** [fengkaijia/iplacard#1]
Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php
在index.php找到了这一行，但是不知道该如何配置，请问能否给出一个ubuntu的temple？感谢。

**Comment by fengkaijia** [comment]
按照顺序安装的话框架目录位于 ```vendor/codeigniter/framework/system``` 下，如果此目录不存在，说明 Composer 没有安装；如果此目录存在，有可能是 ```www-data``` 用户无此目录权限。未公开前 iPlacard 是用 Ubuntu 系统 Repo 中的 LNMP 运行的，并不需要特别模板。Nginx 和 Apache 的参考配置文件在 ```resource``` 目录下有。

**Comment by Guochengjie** [comment]
我重新部署了一遍预编译文件，仍然报错
Not Found
The requested URL /account/login was not found on this server.
跳转到account/login
请问如何解决

**Comment by fengkaijia** [comment]
```
define('IP_DOMAIN', '');
```

这项配错了，访问时会先跳转到登录页，但你的配置下跳转到了不存在网址。

**Comment by Guochengjie** [comment]
已经发现错误所在，是未设置伪静态。
