### ISSUE TITLE
[404 Not Found] The requested URL /account/login was not found on this server.

### ISSUE THREAD

**Issue by HazyFish** [fengkaijia/iplacard#10]
I have followed the exact procedures in README.md to setup the website and configured Apache. The php is able to redirect the url to http://[hostname]/account/login, but I got "[404 Not Found] The requested URL /account/login was not found on this server."

**Comment by fengkaijia** [comment]
You need to edit your Apache vhost config, such as ```/etc/apache2/sites-available/000-default.conf```, and change ```AllowOverride``` to ```all```. For detail, check out tutorials such as [this](https://www.digitalocean.com/community/tutorials/how-to-rewrite-urls-with-mod_rewrite-for-apache-on-ubuntu-16-04).

**Comment by HazyFish** [comment]
It works! Thank you very much!
