### ISSUE TITLE
The email function is not working

### ISSUE THREAD

**Issue by HazyFish** [fengkaijia/iplacard#11]
The email that contains the random password cannot be delivered to the applicant's mail box.

**Comment by fengkaijia** [comment]
By default, iPlacard use PHP's [mail()](http://php.net/manual/en/function.mail.php) for delivery. This is rather a PHP/Linux configuration issue that is beyond iPlacard. Please refer to related documents. You may also consider sending email via [SMTP](https://github.com/fengkaijia/iplacard/blob/master/config.example.php#L75).

**Comment by HazyFish** [comment]
I learned that most of the cloud service providers block the port 25 (used for SMTP) by default, and that's causing my problem. After contacting the support team of my VPS provider, they unblocked the port and the email function works now!  

After testing, the emails sent to NetEase 163 works well, the emails sent to Outlook will be marked as Spam, and the emails sent to Gmail doesn't work at all. I know this shouldn't be an issue of this project, but is there any solutions?

**Comment by HazyFish** [comment]
I tried to set up my own SMTP server, but the emails sent by the server will be marked as spam or be rejected too, although I've added MX, PTR, and SPF DNS records to make the emails more likely to be recognized as legitimate ones.

**Comment by fengkaijia** [comment]
1. Setup reverse DNS will help.
2. Check if your IP address is on any blacklist with tools like [https://mxtoolbox.com/blacklists.aspx](https://mxtoolbox.com/blacklists.aspx).
3. Enable encryptions etc. in your Postfix config.

For Gmail, you may use "show original", it usually contains info why the email is labeled spam. If still doesn't work, consider hosted SMTP services.
