### ISSUE TITLE
profile_addition_general问题请教

### ISSUE THREAD

**Issue by Guochengjie** [fengkaijia/iplacard#5]
请问格式如何？我以如下格式添加时后台是乱码且没有文本框。感谢
{"qq": "QQ", "grade": "年级", "choice": "委员会意向 以下可选：北大西洋公约组织（科索沃），安全理事会（南奥塞梯冲突），主新闻中心（南奥塞梯冲突），欧洲安全与合作组织（网络安全与国际反恐），主新闻中心（网络安全与国际反恐）", "gender": "性别", "idcard": "身份证", "school": "学校", "wechat": "微信", "experience": "参会经历（详细）", "socialexperience": "社会经验"}

**Comment by Guochengjie** [comment]
如果我想添加一个学测的框如何添加？感谢。

**Comment by fengkaijia** [comment]
```
{"hotal_special":{"type":"textarea","title":"住宿特殊要求","text":"如果您选择预订友谊宾馆，请在此处填写住宿特殊要求。","default":"","required":false,"enabled":true}}
```

其他格式请阅读代码。
