### ISSUE TITLE
启用SSL后出现由gravatar引起的mix content错误

### ISSUE THREAD

**Issue by Guochengjie** [fengkaijia/iplacard#6]
请问如何解决或者关闭gravatar？

**Comment by Guochengjie** [comment]
经检查，index.php中关于SSL的变量配置正确：
`//是否使用访问SSL`
`if(isset($_SERVER['HTTPS']))`
`{`
`        if('on' == strtolower($_SERVER['HTTPS']))`
`                define('IP_SSL', true);`
`        if('1' == $_SERVER['HTTPS'])`
`                define('IP_SSL', true);`
`}`
`if(!defined('IP_SSL'))`
`        define('IP_SSL', true);`

**Comment by fengkaijia** [comment]
请自行排查，Gravatar属框架函数，不受```IP_SSL```管理，只要PHP存在```$_SERVER['HTTPS']```变量即使用SSL域名，与iPlacard无关。
